version: "3.9"

services:
  app:
    build: .
    container_name: ubnd_api
    environment:
      - PORT=8080
      - PREFIX_API=/api
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

