import express from 'express';
import authRoute from './auth.route.js';
import userRoute from './user.route.js';
import mauDonRouter from './mau-don.route.js';
import uyBanRouter from './uy-ban.route.js';
import thuTucRoute from './thu-tuc.route.js';
import linhVucRoute from './linh-vuc.route.js';
import coSoDichVuCongRoute from './co-so-dich-vu-cong.route.js';
import tinTucRouter from './tin-tuc.route.js';
import danhMucTinTucRouter from './danh-muc-tin-tuc.route.js';
import lichTiepDanRouter from './lich-tiep-dan.route.js';
import linhVucPhanAnh from './linh-vuc-phan-anh.route.js';
import phanAnhRouter from './phan-anh.route.js';
import videoUploadRouter from './video-upload.route.js';
import logRouter from './log.route.js';
import reportRouter from './report.route.js';
import notificationRouter from './notification.route.js';
import permissionRouter from './permission.route.js';
import roleRouter from './role.route.js';
import auditLogRouter from './audit-log.route.js';
import exportRouter from './export.route.js';
import addressVoteRoute from './address-vote.route.js';
import dangKyTiepDanRouter from './dang-ky-tiep-dan.route.js';
import receptionScheduleRouter from './reception-schedule.route.js';
import receptionScheduleManagementRouter from './reception-schedule-management.route.js';
import receptionRatingRouter from './reception-rating.route.js';
import receptionCounterRouter from './reception-counter.route.js';
import receptionCounterAssignmentRouter from './reception-counter-assignment.route.js';
import receptionShiftAssignmentRouter from './reception-shift-assignment.route.js';
import leaderMeetingScheduleRouter from './leader-meeting-schedule.route.js';
import leaderMeetingRegistrationRouter from './leader-meeting-registration.route.js';
import leaderMeetingRatingRouter from './leader-meeting-rating.route.js';
import taiLieuVanHoaRouter from './tai-lieu-van-hoa.route.js';
import taiLieuPhapLuatRouter from './tai-lieu-phap-luat.route.js';

const rootRouter = express.Router();

rootRouter.use('/auths', authRoute);
rootRouter.use('/users', userRoute);
rootRouter.use('/mau-don', mauDonRouter);
rootRouter.use('/uy-ban', uyBanRouter);
rootRouter.use('/thu-tuc', thuTucRoute);
rootRouter.use('/linh-vuc', linhVucRoute);
rootRouter.use('/co-so-dich-vu-cong', coSoDichVuCongRoute);
rootRouter.use('/tin-tuc', tinTucRouter);
rootRouter.use('/danh-muc-tin-tuc', danhMucTinTucRouter);
rootRouter.use('/lich-tiep-dan', lichTiepDanRouter);
rootRouter.use('/linh-vuc-phan-anh', linhVucPhanAnh);
rootRouter.use('/phan-anh', phanAnhRouter);
rootRouter.use('/video', videoUploadRouter);
rootRouter.use('/logs', logRouter);
rootRouter.use('/report', reportRouter);
rootRouter.use('/permission', permissionRouter);
rootRouter.use('/role', roleRouter);
rootRouter.use('/report', reportRouter);
rootRouter.use('/notifications', notificationRouter);
rootRouter.use('/audit-logs', auditLogRouter);
rootRouter.use('/export', exportRouter);
rootRouter.use('/address-vote', addressVoteRoute);
rootRouter.use('/reception-registrations', dangKyTiepDanRouter);
rootRouter.use('/reception-schedules/management', receptionScheduleManagementRouter);
rootRouter.use('/reception-schedules', receptionScheduleRouter);
rootRouter.use('/reception-ratings', receptionRatingRouter);
rootRouter.use('/reception-counters', receptionCounterRouter);
rootRouter.use('/reception-counter-assignments', receptionCounterAssignmentRouter);
rootRouter.use('/reception-shifts', receptionShiftAssignmentRouter);
rootRouter.use('/leader-meeting-schedules', leaderMeetingScheduleRouter);
rootRouter.use('/leader-meeting-registrations', leaderMeetingRegistrationRouter);
rootRouter.use('/leader-meeting-ratings', leaderMeetingRatingRouter);
rootRouter.use('/tai-lieu-van-hoa', taiLieuVanHoaRouter);
rootRouter.use('/tai-lieu-phap-luat', taiLieuPhapLuatRouter);

export default rootRouter;

